init python:
    event('alexia_lends_a_hand', triggers="npc_events", conditions=("get_actor_job('alexia')=='forge'",), depends=('after_drinking_greyhides_alchol',), run_count=1, group='alexia_forge', priority=pr_npc)


label alexia_lends_a_hand:

scene alexia_forge_1 with fade

"Alexia once again spent the week in the forge, helping out the blacksmith with his duties. This week, however, disaster had struck - there had been trouble on a number of routes between the mines and the portals back to the castle, meaning that numerous deliveries of iron were late."
"She spent most of her time cleaning and running errands, but as the week’s end approached, and more late deliveries began to pile up, there was still much to do."

scene bg22 with fade
show alexia forge neutral at midleft with dissolve
show greyhide neutral at cliohnaright with dissolve

gh "Is that all of the iron accounted for?"

al "I think so. I counted it as the orcs brought it in, and it seems about right. It is hard to tell with only estimates from the mines though."

gh "I see. Well at least it is finally here, but it doesn’t leave us much time to turn it into weapons and armour."

al "Perhaps we could get some more help?"

gh "I doubt it, and even if we could, orcs hardly make for the best assistants."

"Alexia smiled at him, but the minotaur did not smile back, he was deep in thought about how to deal with the current predicament. "
"The silence was broken by the sound of the door opening."

show andras displeased at edgeleft with moveinleft

an "Are my weapons ready, blacksmith?"

al "Not yet, there has been a delay because-"

"The demon turned to look at her and snarled."

an "Was I talking to you, woman?"

"Alexia looked down at the floor, as not to meet his eyes."
 
al "No…"

an "Then spare me your excuses."

gh "As Alexia was going to say before you so rudely cut her off, whelp, the deliveries were delayed, and as a result, I find myself behind."

an "I’m as interested in your excuses as I was in hers. I want those weapons by the end of the week, beast."
an "And if they aren’t ready, I’m sure there are plenty of old broken down minotaurs who can take your place when I snap your neck."

show alexia forge concerned at midleft with dissolve

al "Andras!"

"Andras ignored the woman’s protestations and turned to leave."

an "This week, Greyhide, or else."

hide andras with moveoutleft

al "I am so sorry, Greyhide, he shouldn’t talk to you like that."

#show alexia angry

al "It makes me so angry!"

"The minotaur smiled and placed one of his large hands on her shoulder."

gh "It is okay, child, others have said much worse to me."
gh "No minotaur is able to live as long as I have without enduring many, many, threats, believe me."

show alexia forge neutral at midleft with dissolve

al "Oh…"
al "Well, what do you propose we do? I doubt Andras was bluffing…"

gh "No, I suppose he was not. And even if he were, it would not do to fall behind with more deliveries due next week."
gh "Before we know it, iron will be piling up everywhere, and we can’t be having that now, can we?"

"He let out a laugh and then removed his hand from her."

gh "No, Alexia, we do the only thing we can do."
gh "We work."

scene alexia_forge_1 with fade

"They spent the rest of the day working hard, sweating amidst the heat generated by the castle’s furnace. Alexia would go and fetch iron as the inhumanly strong minotaur beat, shaped, and cooled various blades, plates, and other necessary elements for the needed equipment."
"Alexia would do her best to place together, or affix the pieces when he was done, as she had little skill at smithing herself. It took them all day, but by the end, it seemed like finishing over the next two days was a possibility, and that Greyhide’s head was probably safe. At least for now."

scene bg22 with fade
show alexia forge neutral at midleft with dissolve
show greyhide neutral at cliohnaright with dissolve

al "Phew… That should do it for today."

gh "Yes, I think we might even catch up at this rate. But I’m afraid the work will be just as bad tomorrow."

"Alexia smiled at him, in an attempt to allay his guilt. "

al "I don’t mind the work Greyhide, to be honest, it keeps my mind occupied so I don’t have to worry about my situation."

"The minotaur was silent, worried that he had inadvertently touched a sore point. Not everyone at the castle had chosen to come here after all. Alexia noticed his unease. "

al "Say, master Greyhide?"

gh "Hmm?"

al "I know I’m not much in the way of a smith, but maybe you could teach me how to make a blade?"

gh "There’s no shame in that child, I’m sure there are plenty of other things you are good at."

al "Well, I’m a pretty good dancer…"

gh "There you go, could you imagine me dancing? I’m sure you are much better at smithing than I am on my feet."

"She giggled, the idea of Greyhide dancing was quite funny, she had to admit."

gh "Maybe you can teach me one day, but for now, how about we try that blade?"

"The minotaur picked up a long tang and a pair of tongs and gave them to Alexia. She gripped the handle of the tang with the tongs and held it over the furnace until the end of the metal turned orange from the intense heat."

gh "Now, as you can see, the metal is currently too thick to make a decent blade, we need to draw it out."

al "That is what you are doing when you hit it with the hammer?"

gh "That’s right. Now, here, place it on the anvil."

"The redhead removed the tang from the forge and placed it on the anvil as instructed. The minotaur handed her a small hammer."

al "So, I just hammer it a few times?"

gh "Yes, the part where the metal is heated. Give it a good three or four hits. The metal will become thinner and lengthen, but it won’t grow any wider."

"Alexia lifted the hammer and brought it down a few times, as hard as she could."

al "Like this?"

gh "No, it requires more force. Here."

hide alexia
show greyhide neutral at center with moveinright
show alexia forge neutral at midleft with dissolve

"Greyhide moved behind her and wrapped his much larger hand around hers. Leading her firmly, but gently, he raised the arm again and brought the hammer down harder with the aid of his own strength."

gh "Like this. Now turn it over, otherwise, you’ll end up with ridges on the other side, and we don’t want that."

"The blade was now smooth, but being in such close proximity to the human was having an effect on Greyhide. The smell of her hair and the closeness of her body caused his loins to stir. With the two pressed together, Alexia could feel the huge, semi-hard member press against her back."

show greyhide neutral at edgeright with moveoutright

gh " I’m so sorry, Lady Alexia, I didn’t mean-"

al "It is okay, Greyhide. It is only natural."

al "If anything, I take it for a compliment! I feared you only fancied me after a couple of drinks. "

"She winked, hoping to diffuse the situation with a joke, but Greyhide’s expression darkened at the mention of the firegrout. "

gh "Lady Alexia, I… "

al "Shh, I know. "

if further_sex_scenes_with_greyhide == False:
    "She smiled understandingly at the minotaur. She could see he still felt bad about everything that happened back then."
    "Once Jezera’s interference was discovered, she and Rowan decided that it was all just the alcohol and magic talking, and that they would keep their relationship with Greyhide friendly. But now…"
    "Now with Greyhide’s towering figure before her eyes, his sweat and musk teasing her nose, and the heat of the forge mixing with the heat of her body, she wondered if she really wanted to stand by that decision. It felt like they made it so long ago…"

    menu:
        "Make a move on Greyhide, Rowan be damned":
            $ released_fix_rollback()
            "She rubbed her thighs together. Damn it, the thought of having that bull beneath her was making her hot. Usually, she tried not to think about it, but now..."
            "Ah, to hell with it!"
            $ change_corruption_actor('alexia', 5)
            jump helpForgeSex
            
        "Stay true to your promise with Rowan.":
            $ released_fix_rollback()
            show alexia forge concerned at midleft with dissolve
            "She shook her head slightly, banishing the nefarious thoughts that crept into her head. The decadent atmosphere in the castle was getting to her."
            jump helpForgeNoSex

else:
    "Luckily for Greyhide, Alexia and Rowan did not share his unease with regards to what happened. She already had Rowan’s permission to play with the minotaur, so all she had to do was assuage his fears… "
    
    menu:
        "Make a move on Greyhide.":
            $ released_fix_rollback()
            $ change_corruption_actor('alexia', 5)
            jump helpForgeSex
            
        "She shouldn’t do anything without Rowan.":
            $ released_fix_rollback()
            "Alas, perhaps now was not the right time for that… "
            show alexia forge concerned at midleft with dissolve
            jump helpForgeNoSex


label helpForgeNoSex:

al "Do you want a moment to… Collect yourself?"

gh "Yes. Excuse me, my Lady."

hide greyhide with moveoutright

"She smiled warmly as he left the chamber. Another man would try to initiate something, but not Greyhide. Such a gentle soul… "

scene alexia_forge_1 with fade

"The issue dealt with, the two was free to return to work, without further accidents interfering with their schedule. Miraculously, they were able to meet Andras' quota, and Greyhide was able to avoid his wrath, much to the relief of both of them."

return



label helpForgeSex:

al "There is nothing to be ashamed of Greyhide. Besides..."

"Alexia put the tang down on the anvil and took a step towards the minotaur, flashing him a coy smile."

show alexia forge neutral at midright with moveoutright

al "The feeling is mutual."

gh "Alexia, I don’t think-"

al "Shhh."

#cg1
scene black with fade
show alexia forge neutral behind black
show greyhide neutral behind black

"She took a few more steps until she was before him. With how much taller the minotaur was, she didn’t even have to kneel as she freed his huge phallus from his pants."
"He began to protest, but Alexia shushed him again, as she gently stroked his cock with both of her hands, coaxing it to full hardness."   

al "You just let me take care of everything, okay?"

"She had felt the minotaur’s cock before, but she had yet to taste it, and even though it was far too large to ever fit in her mouth, that wasn’t going to stop her."
"Leaning slightly down she was hit with a strong animal musk, almost overpowering, and nothing like the smell of that of a human. It only served to make her more curious about how the beast would taste."
"Continuing to stroke the shaft with both hands, Alexia softly kissed the top of the minotaur’s massive prick, before beginning to lick it. Like the smell, it had a strong taste, one that she did not find unpleasant."  
"Greyhide let out a grunt of pleasure as she continued to run her tongue around his member, coating it with her saliva. After all, it would have to be very lubricated for what she intended to do once she’d finished enjoying the taste of his cock."
"The pleasure had caused Greyhide’s initial apprehension to dissipate, as he no longer objected to Alexia’s ministrations. He watched eagerly as the human woman worshipped his huge bull dick."
"She continued to hungrily lick, tongue, and kiss it all over as she stroked. Then suddenly, she stopped and stood back straight."

al "Now, lie down."

gh "Huh?"

al "All this foreplay is fine, but there’s nothing like the real thing."

"Greyhide looked at her as it dawned on him what she intended, worried."

gh "But Alexia, you can’t! It is too big."

al "Perhaps, but I certainly aim to try, so be quiet and lie down."

"The minotaur knew when he was beaten and did as he was told. The redhead removed her clothes and positioned herself above him. She spread her legs as far as she could, and begin to lower herself down onto the giant prick below her."

#cg2
scene cg282 with fade
show alexia necklace naked aroused behind cg282
show greyhide neutral behind cg282
pause 3

"It wasn’t going to be easy, that was for sure, but the poor minotaur hadn’t had proper sex since his lover had died, and Alexia was determined to do the best that she could to help on that front."
"It took some work, and a lot of lubrication, but she was able to work the huge tip of the minotaur’s dick past the opening of her snatch." 
"That alone was enough to make her feel almost full enough to burst, but she wasn’t finished. She started to slowly and surely push herself down, taking as much inside her as she could."
"Once she reached her limit, she lifted herself up again and then did the same. It took a while, but eventually, she was able to get a good rhythm going, as the minotaur groaned and grunted below her."
"She felt impossibly full as she ground her hips up and down, moaning loudly as she did so."

al "Gods, it is so big, I didn’t think…"
al "Hnnn!!"

"Alexia felt a long way of orgasmic bliss hit her as she impaled herself on his dick. It throbbed inside her against her walls.  The minotaur was close too."

gh "Alexia, I’m... I’m…"

if all_actors['alexia'].corruption < 31:
    al "That’s it, Greyhide, cum with me… Uhhh…"

elif all_actors['alexia'].corruption > 30 and all_actors['alexia'].corruption < 61:
    al "Oh fuck yesss…. Cum!!!"

else:
    al "Fuck Yes!! Breed me, you beast!!"

#cg2 - cumshot
show cg282 with sshake
show cg282 with sshake
scene cg283 with flash
pause 3

show greyhide neutral behind cg283

"Greyhide let out a loud bellow, shuddered and unleashed his seed deep within her. His load was far larger than that or a human, and when his cock plopped out after cumming, jizz leaked from Alexia’s gaping cunt."

show alexia necklace naked behind cg283

al "Oh dear, it looks like you have made quite the mess."

gh "I’m sorry, I didn’t intend…"

al "Shh, you."

"She kissed him softly on his snout."

al "Everybody gets lonely, we all have needs. "
al "You’ve been on your own for a long time, and I wanted to do something to help you. That is all there is to it, so there is no need for none of your typical moodiness about this, okay?"

"The aforementioned typical moodiness on his face transformed into a smile."

gh "Yes… Thank you Alexia."

"Alexia stood up and picked up her clothes from where she had discarded them nearby."

if further_sex_scenes_with_greyhide == True:
    al "And if you’re still unconvinced… Next time I’ll invite Rowan along, so we can hammer the point in together. "
    gh "Lady Alexia, please. I am not worthy of such friends. "
    al "I think you’re the only person in this castle that truly understands the meaning of this word. You give yourself too little credit Master Greyhide."

al "Now, we’d better get back to work. It wouldn’t do for you to lose your head because I decided to take advantage of you."

scene alexia_forge_1 with fade
"Alexia smiled warmly, and once again assured him that it was fine. The rest of the day passed with a small amount of awkwardness, but the rest of the week was free from incident."
"The pair were able to catch up, sparing Greyhide from Andras’ wrath, much to the relief of the both of them."
return
