# descriptions for the buildings

init python:
    buildings_descriptions = {
        'tavern': "On the long road between the Empire of Sand and the great Forest of Ealoaen, lies the ruins of what was once a sanctuary in the bleak Rakshan Wastes.  This tavern could be restored and used as a means of generating wealth to support the reconstruction of Castle Bloodmeen.  A portal site lies nearby, making it an ideal location to build and allowing staff to easily move between the two.  As the tavern grows and more traders take the overland route again, rumors and whispers will flow from these wooden walls.  The tavern will also serve as the perfect place to establish mercenary contracts.\
Building the tavern will allow you to trade with villages instead of occupying or destroying them.  This will pull in a small amount of income without needing to spend military forces on defeating the local defenders.  However, it will prevent you from removing the village's military capacity from its realm.\
Once the tavern is finished, it will be possible to find family members, business partners, or charitable sorts that are willing to ransom our prisoners for a larger amount of money than we'd get for simply selling them as slaves.  This is a slow process, and we will only be able to ransom a few prisoners each week.",
        'forge': "A place where the smiths turn raw ore into works of art, destruction, and protection.  The forge is used to convert materials like iron into useable equipment for your soldiers.  An orc armed with proper metal equipment has nearly twice the military capacity as an unequipped one.  Even if there are no soldiers in need of equipment, gear produced by the forge will sell for much more than raw ore.  Research and upgrades can improve the quality and quantity of equipment produced, as well as eventually learning how to produce magical arms and armor.",
        'sanctum': "A proper army needs more than just soldiers.  The Dark Sanctum is the first step in adding magic users to the twin's forces.  It can accommodate a cadre of incubus and succubus sorcerers that will support the regular armies in times of war, as well as assist in research during times of peace.  In addition to providing their own military strength, each cubi will also add a small multiplier to the overall combat strength of all soldiers in the castle.  They also have the added bonus of helping to keep up morale, given the habit of cubi taking casual lovers from the ranks of troops.  Research and upgrades will allow more magical facilities to be constructed and increase the number of cubis that can be accommodated.\
Once the sanctum is completed, prisoners will be able to be turned over to the cubi to motivate them and inspire breakthroughs in research.  Each prisoner offered will produce an immediate one time research point boost.",
        'arena': "As the armies of the twins grow larger, they also grow more restless.  A fighting arena will provide the perfect place to blow off steam and keep spirits up.  However, this expensive facility will not provide many other benefits and should only be considered for construction if morale becomes a problem.  Upgrades will increase the capacity for entertainment.\
Once the arena is completed, prisoners may be used as gladiators and fodder for the soldiers.  They won't last long, but will give a significant boost to morale during their last days.",
        'caravan': "The principle supplier for nearly everything the castle has and needs is the goblin caravans, specifically those belonging to the Cla clan.  Thanks to their exclusive access to the portal network for the purposes of trade, they are among the most well positioned traders in all of the Six Realms.  If you need it and have the coin to pay for it, they can probably get it.\
Improvements to Min's caravan fleet run the gambit from better wagons, better draft animals, and more staff to more contacts, better trade deals, and bribing the correct people to insure they're not disrupted by xenophobic locals.  These improvements will not only allow them to make more money while trading goods, but also expand the available stock of equipment for purchase.",
        'hall': "The principle supplier for nearly everything the castle has and needs is the goblin caravans, specifically those belonging to the Cla clan.  Thanks to their exclusive access to the portal network for the purposes of trade, they are among the most well positioned traders in all of the Six Realms.  If you need it and have the coin to pay for it, they can probably get it.\
A more impressive court will make our subjects more willing to comply and places us in a better negotiating position.  Restoring the castle's grandeur will not be a simple or inexpensive task, but will certainly have an impact on on the impressionable and those with darkness in their hearts.  It will also allow Jezera to improve and upgrade the general infrastructure of the entire surface half of the castle.",
        'dungeon': "A section of the underground dedicated to holding prisoners. These are generally acquired after towns or fortresses have been sacked and can later be, employed, in other roles based on what structures we have completed in the castle. However, selling slaves will always be available should some quick money be needed.\
Upgrades here will increase the amount of prisoners that can be kept at once.",
        'library': "The Bloodmeen library is one of the most extensive and well stocked collections in the whole of the Six Realms.  Cliohna has taken possession of it and uses it for both her own personal projects and as the center of operations for the magic and research projects of the castle. Expanding on the collection of books available must be done by finding libraries and abbeys in the world.\
However, what can be done here is investing our treasury into expanded laboratory facilities, equipment, and training staff for the library. These will allow Cliohna to both handle more magical related infrastructure in the castle and expand the scope of her research on Bloodmeen's behalf.",
        'quarters': "The living quarters is a collective term for the staff and guest rooms on the Eastern side of the castle. Much of the initial reconstruction period was spent restoring these areas to a comfortable condition, though there was still much improvement that could be done from the initial state it was brought to.\
Improvements here will make those living in the castle more comfortable and recover from sickness and injury more quickly.",
        'barracks': "A facility for housing and training orc soldiers.  Every week, any new soldiers that Andras has recruited and trained will be brought here and added to the total available soldiers. They will also be armed and armored with any available equipment from a forge, should we have one.\
Expansions and upgrades to the barracks with increase the amount of soldiers that can be kept on hand for any missions or conquests they are needed for. However, the more soldiers we have at once the more we will have to pay and the more difficult it will be to keep morale up. Other infrastructure will be needed to handle the needs of the soldiers.",
        'workshop': "This room, which serves as my planning and drafting room for all construction projects as well as ongoing excavations of the castle tunnels. This space is also where I tend to my hobbies and keep my tools.  Most of the actual work for any building projects will take place on-site, so upgrades and improvements to this building will be unnecessary.",
}
