# entries for quest log
init python:
    quests_entries = {
        'orciad': {
            'title': 'Orc-iad',
            'descr': """A large orc horde has stopped just South of the Rosarian Valley.  The cause is a dispute between the elder chief Ulcro and the young warrior Batri over ownership of an attractive woman that Batri captured in a raid.  The soldiers are useless to Bloodmeen until this conflict is resolved.""",
            'notes': {
                'note1': """A female orc of high standing named Tarish has said that she will be able to bring the horde under her control after arranging for both Ulcro and Batri to be killed by making the woman into a sex slave for the horde as a whole.  In return for arranging this, she will make the hoard serve Bloodmeen.""",
                'note2': """I was turned away from Batri's tent. I will need to prove my worth on a raid before the guard will let me through to meet the rival for the warchief title. I should be able to find a raiding party to join by exploring the camp.""",
                'note3': """I was turned away from Ulcro's command tents. The guard instructed me to bring a weapon as a gift for the warchief to gain access.  Pretty much anything of reasonable quality should do, Cla-Min has plenty available for purchase from her caravan.""",
                'note4': """It seems that Ulcro has refused to fight Batri in ritual combat for the position of warchief. Batri thinks he can force Ulcro to accept the challenge if he can get his hands back on the noblewoman that he captured on a raid and believes is rightly his.  He needs to know where the noblewoman is and have his power strengthened so he can overpower Ulcro's guards and retrieve her.""",
                'note5': """Ulcro claims he has fallen in love with the noblewoman that Batri captured on his raid and is trying to make her comfortable in the camp. He says he will serve Bloodmeen if enough high class comforts such as a better bed, clothing, or food is brought to him.  I should speak to the noblewoman to find out what she thinks of this.""",
                'note6': """I've discovered where Ulcro has hidden the noblewoman. I just need to sneak into her prison so I can talk to her. I'll only be able to try once a week. If I fail, I'll need to come back again on the next week.""",
                'note7': """The noblewoman is Lady Eleanor Delane, she's from one of the lesser houses along the Southern edge of the Rosarian Valley. She's been holding up rather well considering her situation. Neither of the orc chiefs have done much to earn her favor and she is quite suspicious of me right now.  However, she does enjoy my company, so I should be able to earn her trust over time, if I want Tarish's help, or convince her to accept Ulcro.  I can only visit her once a week safely, so it may take some time to accomplish my goal.""",
                'note8': """In order for Batri to take control of the army, he needs to increase his standing in the camp. Going on raids with his men will probably be the easiest way to do this. I might also be able to use some of the castle's resources to help him.""",
                'note9': """I should visit Greyhide and see if he can help arm Batri's soldiers with better equipment.""",
                'note10': """I've hit a bit of a roadblock. If Ulcro believes he's rescuing his love, it might give him the strength to triumph over his rival in the ensuing contest. If I mean to help Batri take the horde, I will need to break Delane first, so Ulcro sees her willingly hanging from Batri's shoulder.  I can't do this myself, I will need agents that have the correct skills.  Building the brothel will be necessary, and if not yet possible I will need to have Cliohna research how to do it.""",
                'note11': """I've hit a bit of a roadblock. If Ulcro believes he's rescuing his love, it might give him the strength to triumph over his rival in the ensuing contest. If I mean to help Batri take the horde, I will need to break Delane first, so Ulcro sees her willingly hanging from Batri's shoulder.  One of our succubus or incubus spies should be able to make Lady Delane more pliable to being Batri's sex slave.  I will be committed to helping Batri if I take this step.""",
                'note12': """I have sent a spy to corrupt Delane into a more willing sex slave. I will need to wait several weeks for this process to be completed.  In the meantime, there is no longer any reason to help Ulcro or plan an escape.""",                
                'note13': """Delane has been corrupted to be much more willing to be Batri's sex slave. There is no longer any reason to help Ulcro or plan an escape.""",
                'note14': """The Lady Eleanor Delane is a very proud woman, I doubt she'll be swayed to stay with Ulcro with gifts alone. I will need to convince her of the value of accepting the warchief before I can secure Ulcro's power here, in addition to finding material comforts for her.  I should should be able to find some if I join the orcs on their raids. Afterwards I should give them to Ulcro.""",
                'note15': """While Delane has been convinced there could be value in being Ulcro's concubine, she needs several material comforts to fully accept him. I should should be able to find some if I join the orcs on their raids, then bring them to Ulcro if I want his help.""",
                'note16': """That should be enough gifts for Ulcro to give, I hope at least. The Lady Eleanor Delane is a very proud woman, I doubt she'll be swayed to stay with Ulcro with gifts alone. I will need to convince her of the value of accepting the warchief before I can secure Ulcro's power here.""",
                'note17': """The nobility are fairly well read and I'm sure that Delane would love some reading material to distract her from the boredom of her confinement. I should ask Cliohna if we have any non-essential books that I could give as a gift for her.""",
                'note18': """Some fine jewelry would certainly make a good gift for a noblewoman.  Jezera practises jewelry as a hobby, perhaps I can ask her for some to pass on to Ulcro?  Of course, there will probably be a steeper price for this compared to other options.""",
                'note19': """The lady Eleanor Delane is suspicious of my intentions, but enjoys my company. I will need to visit her several times and spend time with her before I can earn her trust. Only then will she be willing to come with me on a rescue attempt, whether real or staged.""",
                'note20': """I have gained Delane's trust. She's willing to come with me on a rescue attempt... or a staged one so that I can hand her over to Tarish.""",
                'note21': """In order to turn Delane into a slut for the army, Tarish needs something to fill the woman with nothing but wonton lust. Jezera will probably have what I need for this.""",
                'note22': """For Tarish to arrange for both warchiefs to die in their duel against one another, she needs poison. Cla-Min can likely supply what she needs.""",
                'note23': """If I intend to betray the twins here and actually help Lady Eleanor Delane escape from the three orc chiefs, I need to take some time to consider my options and form a plan.""",
                'note24': """I need a loud diversion to attract the guards attention while I sneak Delane out. I need somebody I can trust, or somebody I can exploit. Batri’s men are always looking for a fight with Ulcro’s, a few raids with them should be enough to get them to listen to me…""",
                'note25': """The perimeter around the camp is poorly maintained, but I will not have the time to look for a hole in it with Delane by my side. I have find an exploitable gap… Or someone who would be leading to help Delane escape.""",
                'note26': """Batri should now be ready to capture Delane and then fight Ulcro for control of the horde. I should go to Batri's tent as soon as possible.""",
                'note27': """Batri has everything he needs to end this power struggle and make himself the only chief of the orc army. I should see him as soon as possible.""",
                'note28': """Everything that's needed for Delane to accept Ulcro has been completed. I should visit Ulcro as soon as possible so this power struggle can finally end.""",
                'note29': """Everything is in place for me to stage a rescue attempt and then turn Delane over to Tarish. Once I'm ready to put her plan into motion, I should go see the orc woman.""",
                'note30': """Even though I have not covered all avenues for planning an escape attempt for Delane, I can attempt one now anyway if time becomes pressing. However, there is a greater risk that things will go poorly..""",
                'note31': """The preparations are complete, all that remains is to visit Delane and initiate her escape. I should keep in mind t is unlikely the warchiefs will tolerate my presence after the noblewoman goes missing…""",
                'note32': """I have done everything I need to do in the orc army camp. They will soon be ready to serve the twins.""",
                'note33': """I am no longer welcome in the orc army camp.  I can only wait and see what happens in regards to this mission now. The twins are unlikely to be pleased with this outcome.""",
            },
        },
        'arthdale_restoration': {
            'title': 'Arthdale restoration',
            'descr': """Upon returning to his home village of Arthdale, Rowan discovered that it is still in ruins from the day the twins attacked it.  He has resolved to look into rebuilding the village for his and Alexia's sake.""",
            'notes': {
                'note1': """Find a way to fund reconstruction.""",
                'note2': """Jezera has refused to allow Bloodmeen's treasury to be used for rebuilding, Rowan will have to find another source.  The baron in the capital of Rastedel is his next best option.""",
            },
        },
    }
