# descriptions for researches

init python:
    research_descriptions = {
        'world_and_the_war': "The world is ever shifting, ever changing.  Sometimes it does so more than others, but it always happens.  Even in the eternal forests of the elves.  When the dark lords rise is when the power of chaos is at its strongest and the face of the planet shifts with it.  Once that time ends, Solensia's power reasserts itself and things become fairly stable once more.\n\n\
As the six realms recently finished the war against Karnas, things are still in a relative state of flux.  Determining the current state of affairs and the directions that each realm is taking will assist greatly in planning the twin's takeover.  Armed with this information, we will be capable of steering things in the direction we wish and have greater opportunities at our disposal.",
        'history_of_rosaria': "Rosaria is one of the human realms, steeped in tradition and the ebb and flow of its noble families.  There are nearly fifty such houses of various levels of prominence.  An extensive study of their family trees and accomplishments should assist when working in the upper circles of the realm's society.  We may also discover other useful bits of information including what artifacts can be found there, what creatures call it home, and resources can be exploited for the twin's benefit.",
        'military_tactics': "Our knowledge of military tactics and logistics is, rudimentary at best.  This makes it difficult to effectively manage fighting forces of any significant size and if we want to expand our ability to house troops we will need to change this.  An extensive study of military tactics will be the first step towards directly expanding our military capacities and is necessary if we want to upgrade any barracks we construct.\n\n\
I will be referencing things with Rowan as I do my work, as (at the time of writing) he is not only the most experienced general in the entire castle, he is the only one with any true fighting experience in a leadership role.  The orc clan leader we did have was among the casualties during the diversionary attack at Arthdale.",
        'survivalism_and_cartography': "While Rowan has exceptional skill in travelling through rough terrain, hunting, and passing by enemy forces undetected, his reported maps have, thus far, left a great deal to be desired.  He also seems to have been self taught, so there is likely some tricks unknown to him that can be gleaned from studying survivalism.  Once given the go ahead, I will begin putting together a crash course in survivalism and cartography that should greatly improve his efficiency in the field.",
        'surveying_and_telescopics': "The use of telescopes would be of great assistance to speeding the surveying of territory.  It will allow Rowan and any other exploration teams to get a better understanding of their surrounding terrain from a distance.  Once given the go ahead, I will arrange for the equipment required to make these devices to be delivered here and will begin assembling them.  As telescopic lenses will be of use to my own research, I do not mind paying the cost of the supplies myself.",
        'monster_taming': "In addition to their armies of chaos races, dark lords have traditionally also used horrific monsters in their armies.  These range from the smaller driders and manticores to the larger trolls and tentacle beasts, and also includes the legendary creatures like the chaos dragon Antarax, the titan of Jahandra, and the Bloodworm.  The twins have expressed a perhaps unhealthy interest in pursuing this line of bolstering their forces.  If we are to continue on this path, I will need to catalogue an overview on previous monster taming techniques and determine the basics of constructing facilities to house monsters.\n\n\
The one saving grace is that Jezera has assured me that she will have no problems transporting creatures of any size in and out of the castle, given some time to work and a suitable portal in what will become the breeding pit.",
        'opulence': "Bringing more of the chaos races under the banner of the twins will require diplomacy.  Based on my historical studies, the best place to start will be by creating an impressive and opulent castle.  All races almost invariably respect the biggest and strongest, therefore the more powerful we appear to be, the more attractive we will be as an alliance partner.  The forces that have already been recruited are also more likely to remain loyal if we appear stronger.\n\n\
Jezera has mentioned that such upgrades will also give her time to improve on the castle's surface infrastructure.",
        'dark_subterfuge': "Jezera has insisted that I should preface this item as being high priority, though I don't see anything particularly special about espionage when you consider our overall situation.\n\n\
At any rate, we are now in a position where we can seriously consider building facilities to support a small team of spies in the castle.  The natural candidates for this work will be particularly talented incubi and succubi.  They will offer the opportunity to take more subtle tactics to secure new territory and means of directly gathering intelligence on the six realms instead of relying on rumors and hearsay.",
        'contact_network': "While the facilities in the castle are quite impressive, it is impossible to find everything that one might need for magical and research pursuits in one place.  Therefore I would like to request permission to spend some time traveling around the world in order to establish a contact network that I can use to get any supplies or books I'm missing here.  This will be necessary if we have any intention of expanding my operations in the library, which in turn will be necessary when it comes time to expand the magical branch of the army beyond a limited force.",
        'basic_summoning': "Bolstering the castle's forces with entities conjured out of the primal elements offers two primary benefits.  First of all, these elementals are easily replaced and essentially create a basic amount of military power that the twins will always have access to.  It will also lead into other techniques that can be used to take further advantage of conquests by converting fallen enemies into undead through necromancy, or by sacrificing those taken alive through demonology.",
        'smelting': "During the last war a great innovation spread across the six realms that is likely one of the main contributing factors towards Karnas's defeat.  That is, the new technique of smelting iron.  It is my understanding that a new alloy, steel, becomes possible to make using this.  While it will take further work to determine how to produce this new metal, an extensive study of smelting will allow us to improve our existing forge facilities.  However, this knowledge will not do the twins any good until a forge has been built for the castle.",
    }


    research_reports = {
        'world_and_the_war': "The six realms are spread out to the South and East of castle Bloodmeen and the Rackshan Wastes it unofficially rules over.  In the South, the main realms are the Forest of Ealoaen, then Rosaria, followed by the Frozen Tundra.  To the East are the Empire of Sand and the Dragon's Tail.   Lastly, in the center of them all, is the Holy City of Prothea and its small dominance.\n\n\
For the most part, the years after the war have been that of peace and rebuilding, though there are always some machinations of the ambitious and petty.  However, these squabbles have been limited to internal realm struggles.  There are currently no open hostilities between any of the six realms.  Similarly, there are no official alliances or pacts between any realms, save with Prothea.  The other five realms pay at least some form of tribute to Prothea and recognize it as their final religious authority.  Rosaria has the strongest ties, being the one closest to the Holy City geographically.\n\n\
All of the realms are still dealing with the remnants of Karnas's armies as well as various crises and distractions.  As each is primarily concerned with internal affairs, now is an excellent time to gather strength in preparation to move against them.  Until we play our hand and actually invade or turn a realm to our side, it is extremely unlikely that any of them will take steps to undermine us as a united force.\n\n\
If directed, I may continue these studies with a more focused study on any of the Six Realms.\n\n\
{b}More specific reports about each realm you may visit are now available to you in the Throne room.  These will be regularly updated with any new information gathered from our agents.  New options have been unlocked in events.{/b}",
        'history_of_rosaria': "Landscape - The primary terrain is arable land, with smaller patches of wooded land, swamp, and hills. The main exception is the large forest, the Blackholt Woods, in the east of the realm. From its source high in the mountains of the East, the river Yael runs east through Rastedel, before splitting into two main tributaries; one flowing further west to the sea, the other heading south to disappear under the Broken Mountains. In the north, the Rosarian valley cuts across the realm, separating the lower part from the Holy Kingdom of Prothea further north, and the giant trees of the Forest of Eoloaen.\n\n\
Demographics - The population of Rosaria is largely human, and for the most part the work in industries that benefit the feudal society; either as farmers, or as blacksmiths, potters, crofters, and other tradesmen. More adventurous humans may become travelling salesmen,  or soldiers serving the barony, while the reckless or brave may take up adventuring or monster hunting.  Rarer, but still a common sight in the larger towns are the half-elven, those whose ancestry is at some point tinged with elven blood, and who have, either as the result of choice or by an accident of birth, opted to live outside the darkness of Eoloaen. Much rarer are the pure elven, who rarely venture outside the forest, consumed by the war with their dark brethren, and the drakken (the dragon equivalent of the half elven). Real dragons are so rare that most people in Rosaria (wrongly) think they are extinct.\n\n\
Threats - Due to a poor harvest, banditry is on the rise once again, with rumours have begun to spread of a particularly nasty group hiding out in the western forest. In the north, a savage orc warchief , having broken his alliance with the dark elves and quit the great forest, is amusing himself raiding the local villages. The story of demons destroying a village making its way through the realm has also increased the activity of cultists, and others who seek power through the dark arts. The countryside is also littered with less organized threats, like lone ogres who wander out from the Broken Mountains in search of food, bloody thirsty trolls, the restless dead, and other monsters small and large.\n\n\
Finally, I've prepared a list of all the Rosarian noble houses, the current state of each, and their accomplishments during the last war.  It should be of use to Rowan when dealing with the nobility while he is in Rosaria.\n\n\
{b}New information has been added to the Rosaria realm report.  New options have been unlocked in events.{/b}",
        'military_tactics': "While Andras's reluctance to let anyone tell him what to do makes teaching him difficult, he is at least willing to listen to sense and logic when pressured.  The combined efforts of myself and Rowan have produced results, turning the army underneath us from an undisciplined mob into something that can function with at least some cohesion.\n\n\
Further efforts will be needed to turn this force into an actual professional army, but at the very least the facilities can now be expanded to hold a larger force without fear of that force tearing itself apart.  The next step will be improving our logistics.\n\n\
{b}Level 2 Orc Barracks unlocked.{/b}",
        'survivalism_and_cartography': "I refuse to continue attempting to educate Rowan in the field of survivalism.  I am no longer comfortable in this line of work.  He has been taught how to draw a proper map, I will leave it at that.  If further work is necessary, a new teacher will have to be brought in.\n\n\
{b}Your movement points while exploring have been increased by 2.{/b}",
        'surveying_and_telescopics': "A set of telescopes and other surveying equipment, as well as a few backups, are now prepared.  I will give a brief overview on their use and provide them to Rowan at the first opportunity.\n\n\
{b}Your visibility range while exploring has been increased by 1.{/b}",
        'monster_taming': "I have finished preparing plans for constructing a facility for both breeding and storing monsters.  Currently our understanding is only enough to handle the smaller monsters, such as driders.  More studies will be needed if we wish to add larger creatures to our forces.  I will once again advise caution when using these beasts, as they are difficult to control and very dangerous.  It will be wise not to rely on them too extensively.\n\n\
{b}Level 1 Breeding Pit unlocked.{/b}",
        'opulence': "They say that pride comes before fall, but without pride we will never rise in the first place.  Skordred and I have now finished plans to expand and reclaim more of the surface region of the castle.  He is standing by to begin work as soon as the funds are allocated for such a project.\n\n\
I am also now prepared to begin research on the fields of diplomacy and espionage.\n\n\
{b}Level 2 Castle Hall/Throne Room and level 2 Living Quarters unlocked.{/b}",
        'dark_subterfuge': "The basics of the arts of cubi espionage and infiltration are now ours.  Due to the somewhat petty nature of these succubi and incubi that will be serving as the castle's wing of shadow operatives, we will need to construct a special facility for them before we begin recruiting.  The plans have been prepared, and I'm sure that Jezera will be ecstatic when she learns that construction has begun.\n\n\
{b}Level 1 Brothel unlocked.{/b}",
        'contact_network': "I am pleased to report my success and establishing a contact network throughout the Six Realms.  I'm now in a position where I can see to the expansion of our existing library and magical facilities, in order to have space for more staff, books, alchemical supplies, and magical implements.  Skordred has been briefed on my requirements and is prepared to oversee the expansionary work once ordered and provided the necessary funds.  I've also gained new leads regarding the magical arts of summoning that may now be pursued.\n\n\
As a reminder, expanding the library will be necessary if we wish to have more than a single magical facility under the castle.\n\n\
{b}Level 2 Library and Level 2 Dark Sanctum unlocked.{/b}",
        'basic_summoning': "Thanks to my network of contacts, I've managed to locate a suitable expert in the arts of summoning that has agreed to join us in the castle once we've finished constructing a proper summoning chamber for him to take up residence.  The twins have already met with him and given their approval for the construction plans he has provided.\n\n\
{b}Level 1 Summoning Chamber unlocked.{/b}",
        'smelting': "I've determined a new form of air pump that will allow us to make much larger and hotter forges.  This will allow us to upgrade any existing forges to a larger size and I will be able to follow up on this research to determine the metallurgic components of steel.  After all, we can now make a hot enough forge to actually smelt the metal alloy.\n\n\
{b}Level 2 Forge unlocked.{/b}",
    }
